Fixing stalled terraform plan

diff --git a/.github/workflows/scheduled-drift-check.yml b/.github/workflows/scheduled-drift-check.yml
--- a/.github/workflows/scheduled-drift-check.yml
+++ b/.github/workflows/scheduled-drift-check.yml
@@ -69,18 +69,18 @@ jobs:
         id: terraform-plan
         run: |
           cd terraform
-          terraform plan -detailed-exitcode -no-color
-          export exitcode=0
-          terraform plan -detailed-exitcode -no-color -out=tfplan || export exitcode=$?
+          terraform plan -detailed-exitcode -no-color -input=false
+          # export exitcode=0
+          # terraform plan -detailed-exitcode -no-color -out=tfplan || export exitcode=$?
 
-          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+          # echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
 
-          if [ $exitcode -eq 1 ]; then
-            echo Terraform Plan Failed!
-            exit 1
-          else 
-            exit 0
-          fi
+          # if [ $exitcode -eq 1 ]; then
+          #   echo Terraform Plan Failed!
+          #   exit 1
+          # else 
+          #   exit 0
+          # fi
 
       # Save plan to artifacts
       - name: Publish Terraform Plan
